// src/lib/header.svelte
<script lang="ts">
  import { page } from "$app/stores"
  import { pkgCtx, platformCtx } from "$lib/ctx"
  // import Icon from "$lib/icon.svelte"
  import type { State } from "../routes/+layout.svelte"

  export let state: State

  // pathAの2個分まで対応
  // それ以上にの場合はnavLinksのロジックを変更する必要有
  const navLinks = [
    { path: "/",        name: "Top"     },
    { path: "/about/",  name: "About"   },
    { path: "/blog/",   name: "Blog"    },
    { path: "/works/",  name: "Works"   },
    { path: "/dev/",    name: "Dev"     },
    { path: "/inner/",  name: "Inner"   },
    { path: "/joinus/", name: "JoinUs"  },
  ]
  const navLinksExt = [
    { url: "http://www.kobe-kosen.ac.jp", name: "KCCT" },
    { url: "https://20s.d3bu.net", name: "20s" },
  ]

  $: pathA = $page.url.pathname.split("/").map(s => s + "/")
    .slice(0, -1) // trailingSlash依存
  $: breadcrumbs = pathA.map((name, i) => ({
    name,
    path: pathA.slice(0, i + 1).join(""),
  }))
</script>

<header class:gaming={state.konami} class:z={state.z}>
  <div class="headerLogo">
    <a class="logo" href="/">
      <img class="icon" src="/icon.png" alt="Logo" /><!-- SVGアニメーションにしたい -->
      <span class="text"
        ><span class="inline-block">神戸</span
        ><span class="inline-block">高専</span
        ><span class="inline-block">電算部</span></span
      >
    </a>
    <div class="pkgInfo">
      <span>/api/package.json</span>
      <span>{JSON.stringify($pkgCtx)}</span>
    </div>
  </div>
  <nav class="headerNav">
    <span>&gt; ls /</span>
    <ul class="navLinks">
      {#each navLinks as { path, name }}
        <li class:active={pathA.slice(0, 2).join("") === path}>
          <a href={path}>{name}</a>
        </li>
      {/each}
      {#each navLinksExt as { url, name }}
        <li>
          <a href={url} target="_blank" rel="noreferrer">{name}</a>
        </li>
      {/each}
    </ul>
    <span>&gt; pwd</span>
    <ul class="breadcrumbs">
      {#each breadcrumbs as { path, name }}
        <li>
          {#if path !== undefined}
            <a href={path}>{name}</a>
          {:else}
            <span>{name}</span>
          {/if}
        </li>
      {/each}
    </ul>
    <span>&gt; echo $PLATFORM</span>
    <span>{$platformCtx}</span>
    <span>&gt; _</span>
  </nav>
</header>

<style lang="scss">
  @import "../styles/helpers.scss";
  @import "../styles/variables.scss";

  header {
    display: flex;
    flex-direction: column;
    background-color: $c-headerBg;
    color: $c-headerText;

    &.gaming {
      @include gaming;
    }

    &.z {
      background-color: $c-headerBgZ;
    }

    @include mqDown(md) {
      border-radius: 8px 8px 0 0;
    }
  }

  .headerLogo {
    display: flex;
    height: 4rem;
    margin: .5rem 0;
    justify-content: space-between;
    user-select: none;

    @include mqUp(md) {
      height: 3.5rem;
    }
    @include mqUp(xs) {
      height: 100%;
    }

    .logo {
      display: flex;
      height: 100%;
      position: relative;
      align-items: center;

      @include mqDown(md) {
        margin-left: .25rem;
      }

      .icon {
        height: 3.5rem; // .headerLogo's height
        margin: 0 .5rem;
      }

      .text {
        display: inline-block;
        color: $c-logoText;
        font-size: 2em;
        font-weight: 900;
        line-height: 1.1;

        .z & *:first-child {
          color: $c-logoStar;
        }
      }
    }

    .pkgInfo {
      display: flex;
      height: 100%;
      margin: 0 .5rem;
      flex-direction: column;
      justify-content: flex-end;
      align-items: flex-end;
      color: $c-headerDimText;
      font-weight: bolder;

      @include mqUp(md) {
        display: none;
      }
    }
  }

  .headerNav {
    display: flex;
    padding: .5em;
    flex-direction: column;
    background-color: $c-headerNavBg;
    color: $c-headerNavText;
    font: 1rem/1.8 $f-mono;
    cursor: text;

    .gaming > & * {
      @include gaming;
      color: transparent;
      background-clip: text;
    }

    .z & {
      font-family: $f-correct;
    }

    * {
      flex-wrap: wrap;
    }

    a {
      color: $c-headerNavText;
    }

    .navLinks {
      display: flex;
      margin: 0;

      li:not(:last-child)::after { // 隣接セレクタだと折り返しが厳しい
        margin-right: 1em;
        content: "";
      }

      .active a {
        color: $c-headerNavStrong;
        text-decoration: underline;
      }
    }

    .breadcrumbs {
      display: flex;
      margin: 0;

      li:not(:first-child) {
        margin-left: .1em;
      }
    }
  }
</style>

// app/components/Header.tsx
import { Breadcrumbs } from "@/components/Breadcrumbs";
import { HeaderNav } from "@/components/HeaderNav";
import { HeaderNavLink } from "@/components/HeaderNavLink";
import { konamiAtom } from "@/features/easteregg/atoms";
import { useAxisLabel } from "@/features/easteregg/hooks";
import type { RootLoaderData } from "@/root";
import { Link } from "@remix-run/react";
import { css, cx } from "@styles/css";
import { flex } from "@styles/patterns";
import { token } from "@styles/tokens";
import { useAtomValue } from "jotai";
import { useRouteLoaderData } from "react-router";

const navLinks = [
  { path: "/", name: "Top" },
  { path: "/about/", name: "About" },
  { path: "/blog/", name: "Blog" },
  { path: "/works/", name: "Works" },
  { path: "/dev/", name: "Dev" },
  { path: "/inner/", name: "Inner" },
  { path: "/joinus/", name: "JoinUs" },
];

const navLinksExt = [
  { url: "http://www.kobe-kosen.ac.jp", name: "KCCT" },
  { url: "https://20s.d3bu.net", name: "20s" },
];

export const Header = () => {
  const data = useRouteLoaderData("root") as RootLoaderData;
  const konami = useAtomValue(konamiAtom);
  const axis = useAxisLabel();

  const star = css({ color: "logoStar" });

  return (
    <header
      className={flex({
        direction: "column",
        bg: "header.bg",
        color: "header.text",
        animation: "bgSlide 4s linear infinite",

        md: {
          rounded: "md",
        },
      })}
      style={{
        ...(konami && {
          background:
            "linear-gradient(to right, cyan, yellow, magenta, cyan) center/200%",
        }),
        ...(axis == "left" && { background: token("colors.header.bg.z") }),
      }}
    >
      <section
        className={flex({
          justify: "space-between",
          h: { base: "full", md: "3.5rem", xl: "4rem" },
          my: "0.5rem",
          userSelect: "none",
        })}
      >
        <Link
          className={flex({
            align: "center",
            h: "full",
            pos: "relative",

            md: {
              ml: ".25rem",
            },
          })}
          to="/"
        >
          <img
            className={css({
              h: "3.5rem",
              w: "3.5rem",
              mx: ".5rem",
            })}
            src="/icon.png"
            alt="Logo"
          />
          <p
            className={css({
              color: "logoText",
              fontSize: "2rem",
              fontWeight: "extrabold",
              lineHeight: 1.1,
              cursor: "pointer",
            })}
          >
            <span
              className={cx(
                css({ display: "inline-block" }),
                axis == "left" && star,
              )}
            >
              神戸
            </span>
            <span className={css({ display: "inline-block" })}>高専</span>
            <span className={css({ display: "inline-block" })}>電算部</span>
          </p>
        </Link>
        <p
          className={flex({
            display: { base: "none", md: "flex" },
            direction: "column",
            align: "flex-end",
            justify: "flex-end",
            h: "full",
            mx: ".5rem",
            color: "header.text.dim",
            fontWeight: "bolder",
            cursor: "default",
          })}
        >
          <span>/api/package.json</span>
          <span>{JSON.stringify(data.pkg)}</span>
        </p>
      </section>
      <HeaderNav axis={axis} gaming={konami}>
        <p>&gt; ls /</p>
        <ul
          className={flex({
            gap: "1rem",
          })}
        >
          {navLinks.map(({ path, name }) => (
            <li key={path}>
              <HeaderNavLink to={path} label={name} />
            </li>
          ))}
          {navLinksExt.map(({ url, name }) => (
            <li key={url}>
              <a
                className={css({ color: "header.nav.text" })}
                href={url}
                target="_blank"
                rel="noopener noreferrer"
              >
                {name}
              </a>
            </li>
          ))}
        </ul>
        <p>&gt; pwd</p>
        <Breadcrumbs />
        <p>&gt; echo $PLATFORM</p>
        <p>{data.platform}</p>
        <p>&gt; _</p>
      </HeaderNav>
    </header>
  );
};
