// src/routes/blog/index.svelte
<script context="module" lang="ts">
  export async function load({ fetch }) {
    const { data } = await fetch("/api/articles/blog.json").then(r => r.json())
    return { props: { entries: data } }
  }
</script>

<script lang="ts">
  import Meta from "$lib/meta.svelte"
  import { dateFmt } from "$lib/fmt"

  export let entries
</script>

<Meta title="電算「部」log" description="神戸高専電算部の活動日誌（ブログ）です．" noTitleFormat />

<h1>電算「部」log</h1>

{#each entries as article}
  <article>
    {article.date ? `${dateFmt(new Date(article.date))} - ` : ""}
    <a href={`/blog/${article.slug}`}>{article.title}</a>
    <span class="inline-block">by {article.author || "KCCTdensan"}</span>
  </article>
{/each}

// app/routes/blog.tsx
import { getArticle } from "@/lib/.server/articles";
import { formatDateYMD } from "@/lib/date";
import { extendMeta } from "@/lib/meta";
import { useLoaderData } from "@remix-run/react";

export const loader = async () => getArticle("blog");

export const meta = extendMeta<typeof loader>(() => [
  {
    title: "電算「部」log",
  },
  {
    property: "og:title",
    content: "電算「部」log",
  },
  {
    name: "description",
    content: "神戸高専電算部の活動日誌（ブログ）です．",
  },
  {
    property: "og:description",
    content: "神戸高専電算部の活動日誌（ブログ）です．",
  },
]);

export default function Page() {
  const { data } = useLoaderData<typeof loader>();

  return (
    <>
      <h1>電算「部」log</h1>
      {data.map((article) => (
        <article key={article.slug}>
          {article.date ? `${formatDateYMD(new Date(article.date))} - ` : ""}
          <a href={`/blog/${article.slug}`}>{article.title}</a>
          <span className="inline-block">
            by {article.author || "KCCTdensan"}
          </span>
        </article>
      ))}
    </>
  );
}
